import { MerchItem } from "../types";

const SampleStock: MerchItem[] = [
  {
    featured: false,
    totalStock: 2,
    name: "Product A",
    price: "19.99",
    merchId: "12345",
    imgSrc: "product-a.jpg",
    extraImages: ["product-a-1.jpg", "product-a-2.jpg", "product-a-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "music",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product B",
    price: "29.99",
    merchId: "67890",
    imgSrc: "product-b.jpg",
    extraImages: ["product-b-1.jpg", "product-b-2.jpg", "product-b-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "music",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product C",
    price: "14.99",
    merchId: "54321",
    imgSrc: "product-c.jpg",
    extraImages: ["product-c-1.jpg", "product-c-2.jpg", "product-c-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "music",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product D",
    price: "39.99",
    merchId: "98765",
    imgSrc: "product-d.jpg",
    extraImages: ["product-d-1.jpg", "product-d-2.jpg", "product-d-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "accessories",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product E",
    price: "24.99",
    merchId: "24680",
    imgSrc: "product-e.jpg",
    extraImages: ["product-e-1.jpg", "product-e-2.jpg", "product-e-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "accessories",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product F",
    price: "49.99",
    merchId: "13579",
    imgSrc: "product-f.jpg",
    extraImages: ["product-f-1.jpg", "product-f-2.jpg", "product-f-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "accessories",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product G",
    price: "34.99",
    merchId: "11223",
    imgSrc: "product-g.jpg",
    extraImages: ["product-g-1.jpg", "product-g-2.jpg", "product-g-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product H",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product I",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product J",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product K",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product L",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product M",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product N",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product O",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product P",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product Q",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product R",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product S",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
  {
    featured: false,
    totalStock: 2,
    name: "Product T",
    price: "54.99",
    merchId: "99887",
    imgSrc: "product-h.jpg",
    extraImages: ["product-h-1.jpg", "product-h-2.jpg", "product-h-3.jpg"],
    dateAdded: "",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi expedita officiis perspiciatis praesentium sit quo rerum voluptate at perferendis. Ad consequatur eveniet, id pariatur quidem voluptatibus praesentium ex odio commodi!",
    category: "clothing",
  },
];

export default SampleStock;
