name: Firebase Deploy
run-name: Deploy website to Firebase
on:
  push:
    branches:
      - main
      - test

env:
  NODE_ENV: "PROD"

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Biome Lint Check & Build-step Check
        run: |
          bun i
          bun run lint
          bun run build
  deploy-client:
    needs: lint-check
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Build
        run: | 
          bun i
          bun run build
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Install Firebase CLI
        run: bun add -g firebase-tools
      - name: Deploy to Firebase
        
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=gcp_key.json
          echo '${{ secrets.WEBSITE_SERVICE_ACCOUNT_JSON }}' > gcp_key.json
          bun x firebase experiments:enable webframeworks
          firebase deploy --only hosting -P daydreamers-website